### ISSUE TITLE
Register-SecretVault : Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/SecretManagement#40]
Trying to follow blog post. After installation:

```powershell
Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault
```

```none
Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault

Register-SecretVault : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:1 char:1
+ Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Register-SecretVault], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.SecretManagement.RegisterSecretVaultCommand
```

**Comment by PaulHigin** [comment]
What version of PowerShell are you using and what platform are you running on?
```powershell
$psversiontable
```

Please include error exceptions and inner exceptions.
```powershell
$err = Get-Error
$err.Exception
$err.Exception.Stacktrace
$err.Exception.InnerException
$err.Exception.InnerException.Stacktrace
```

Also include the version of the module you are running:
```powershell
Get-Module
```

**Comment by PrzemyslawKlys** [comment]
```
PS C:\Users\przemyslaw.klys> Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault
Register-SecretVault : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:1 char:1
+ Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Register-SecretVault], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.SecretManagement.RegisterSecretVaultCommand

PS C:\Users\przemyslaw.klys> $Error[0].Exception
Cannot bind argument to parameter 'Path' because it is an empty string.
PS C:\Users\przemyslaw.klys> $Error[0].Exception.Stacktrace
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   at Microsoft.PowerShell.SecretManagement.RegisterSecretVaultCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
PS C:\Users\przemyslaw.klys> $Error[0].Exception.innerexception
PS C:\Users\przemyslaw.klys> $Error[0].Exception.innerexception.stacktrace
PS C:\Users\przemyslaw.klys>
```

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        chocolateyProfile                   {TabExpansion, Update-SessionEnvironment, refreshenv}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Binary     0.5.2      Microsoft.PowerShell.SecretManag... {Get-Secret, Get-SecretInfo, Get-SecretVault, Register-SecretVault...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.1.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
Script     0.87.2     PSWriteColor                        {Write-Color, Write-Colour}
```

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by salbeck** [comment]
FWIW, I have the exact same issue. $error and module-versions match what I have (..secretstore module v0.5.1 although the error is thrown by the Register-SecretVault cmdlet attempting to validate the module)

**Comment by PaulHigin** [comment]
Ok, I have found the problem, thanks for the detailed information.  This is a bug in Windows PowerShell `CommandInvocationIntrinsics.InvokeScript()` method.  The bug was fixed in PowerShell Core but apparently not back ported to Windows PowerShell.  I have been testing mostly in PowerShell Core (v7) and didn't experience it.

But this bug prevents `Register-SecretVault` from working in Windows PowerShell.  Unfortunately, the only workaround is to install [PowerShell Core](https://github.com/powershell/powershell) and register extension vaults there.  The registered extension vaults will work with Windows PowerShell, you just can't register them in Windows PowerShell.

I do have a fix in SecretMangement to workaround this InvokeScript() binding bug.  I am not sure when the next release will be but will try to get it out sooner than later.  In the mean time please use PowerShell Core to register secret vaults.

**Comment by PaulHigin** [comment]
Fixed in Preview4.
